#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt -y update
sudo apt -y install nginx
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
